/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c AlarmControl interfaces/alarmcontrol.xml -a alarmcontrol
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "alarmcontrol.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AlarmControl
 */

AlarmControl::AlarmControl(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AlarmControl::~AlarmControl()
{
    // destructor
}

void AlarmControl::dropCall()
{
    // handle method call org.meego.alarms.dropCall
    QMetaObject::invokeMethod(parent(), "dropCall");
}

void AlarmControl::incomingCall(const QString &summary, const QString &body, const QString &acceptAction, const QString &rejectAction, const QString &sound, const QString &imageURI)
{
    // handle method call org.meego.alarms.incomingCall
    QMetaObject::invokeMethod(parent(), "incomingCall", Q_ARG(QString, summary), Q_ARG(QString, body), Q_ARG(QString, acceptAction), Q_ARG(QString, rejectAction), Q_ARG(QString, sound), Q_ARG(QString, imageURI));
}

