#!/usr/bin/python

import sys
import dbus

if (len(sys.argv) != 3):
	print "Usage: %s SUMMARY BODY" % (sys.argv[0])
	sys.exit(1)

bus = dbus.SessionBus()

control = dbus.Interface(bus.get_object('org.meego.alarms', 
					'/incomingCall'),
					'org.meego.alarms')

control.incomingCall(dbus.String(sys.argv[1]), dbus.String(sys.argv[2]), dbus.String(""), dbus.String(""), dbus.String(""), dbus.String(""))
